name: Test Label WIP checker CI

on:
  pull_request:
    types: [labeled, unlabeled, edited, opened, synchronize, reopened]

jobs:
  test-label-wip-checker-CI:
    runs-on: ubuntu-latest

    steps:
    - name: Test WIP blocker with labels in PR
      uses: Felipebros/github-action-WIP-blocker-with-labels-in-PR@v1.1.2-alpha
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
